name: Workflow with multiple stages

on: push

jobs:
  job-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: pwd
  job-on-windows:
    name: A job running on Windows
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date
      - run: ls
  dependent-job-1:
    needs: [job-on-ubuntu, job-on-windows]
    runs-on: macos-latest
    name: A job that runs on MacOs after first two jobs
    steps:
      - run: pwd
        name: Step 1 in dependent job1
      - name: new step
        run: ls
      - run: env
  dependent-job-2:
    needs: dependent-job-1
    runs-on: ubuntu-latest
    name: A final job
    steps:
      - run: echo Wow this is cool!
      
